version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: garod004-apps-painel-mercado_server_1
      APP_PORT: 8420

  server:
    image: ghcr.io/gabriel-rodrigues-s/painel-mercado:1.0.1
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
